name: Second Action - Single

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello, World!"

  bye_world:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
      - name: Step 1 of Second Job
        run: echo "This is the second job, step 1"
      - name: Step 2 of Second Job
        run: echo "This is the second job, step 2"

  hello_world_2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 of Third Job
        run: echo "This is the third job, step 1"
      - name: Step 2 of Third Job
        run: echo "This is the third

 