name: Second Action - Single

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        type: boolean
        description: Debug
        default: false
        required: false
      sample_value: 
        type: string
        description: Cualquier valor
        default: ""
        required: false
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Hello, World!"

  bye_world:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
      - name: Step 1 of Second Job
        run: echo "This is the second job, step 1"
      - name: Step 2 of Second Job
        run: echo ${{ github.event.inputs.debug_mode }}


 