name: Python Test on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: pip install -r code/requirements.txt

      - name: Run tests
        run: python -m unittest discover -s code -p "test_*.py"


      - name: Run linters
        run: |
          flake8 code

      - name: Run security check
        run: |
          bandit -r code
